title: "Discovery AI Lab"
description: "We explore interdisciplinary research in AI and Biosciences."
baseurl: "" 
url: "https://discoveryailab.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: null

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages
  - assets/css/custom.css

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Add this under 'defaults' if needed
defaults:
  - scope:
      path: ""
    values:
      custom_css:
        - /assets/css/custom.css