title: "Discovery AI Lab"
email: contact@example.edu
description: "Interdisciplinary research at the intersection of AI and biosciences"
baseurl: ""
url: "https://DiscoveryAILab.github.io"
repository: "DiscoveryAILab/discoveryailab.github.io"
#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.24.0

collections:
  teaching:
    output: true
  posts:
    output: true
  projects:
    output: true
  phdprojects:
    output: true
  pages:
    output: true

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
