title: "Discovery AI Lab"
description: "We explore interdisciplinary research in AI and Biosciences."
baseurl: "" 
url: "https://discoveryailab.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: null

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages
  - assets/css/custom.css
  - _includes/head-custom.html

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - bk/


# Enable custom head include
defaults:
  - scope:
      path: ""
    values:
      head_scripts: true
      head_custom: true

