collections_config: {}

paths:
  static: ''
  uploads: uploads

timezone: Europe/London

markdown:
  engine: commonmark
  options: {}

files:
  index.html:
    editor:
      inputs:
        heading:
          type: text
          label: Page Title
          selector: h1
        description:
          type: textarea
          label: Page Description
          selector: p

collections:
  pages:
    path: /
    label: Pages
    files:
      - index.html
