paths:
  uploads: uploads

files:
  index.html:
    editor:
      inputs:
        overview_title:
          type: text
          label: Overview Title
          selector: "#overview h2"
        overview_text:
          type: textarea
          label: Overview Text
          selector: "#overview p:nth-of-type(1)"
        interests_title:
          type: text
          label: Research Interests Title
          selector: "#interests h2"
        interests_text:
          type: textarea
          label: Research Interests Text
          selector: "#interests p"

collections:
  html_pages:
    label: HTML Pages
    path: /
    files:
      - index.html
